#!/usr/bin/env bash

if [ "$1" = "init" ]; then

    # If second argument exists → contest mode
    if [ -n "$2" ]; then
        mkdir -p "$2"
        cd "$2" || exit
        node ~/cp-booster/server/server.js contest

    else
        node ~/cp-booster/server/server.js single
    fi

else
    echo "Unknown command"
fi